### ISSUE TITLE
Testing for one image

### ISSUE THREAD

**Issue by saruvora** [aodiwei/ChineseImg2Cap#1]
Hi !!,
I got your link from show-attend-tell page. I saw your comment for one image [this](https://github.com/yunjey/show-attend-and-tell/issues/54). I see you're also trying to generate for a single image. I have a question were you successful in generating a caption for one image ?

**Comment by aodiwei** [comment]
@saranshvora my way is set one img in a batch, so it is same to batch process, and batch process is works.

**Comment by saruvora** [comment]
@aodiwei Hi, thank you for your immediate response, I tried it but it still gave me that error. But I resolved it by commenting the beta out. 

However, I have one more question have you also worked on hard attention part ? I am working on it using tensorflow but find it a bit difficult to understand it from the paper and even the original implementation from kelvin Xu which is in theano

**Comment by aodiwei** [comment]
@saranshvora sorry，I didn't work on it.
